FROM node:16.17.1-alpine

# 작업 디렉토리 생성
WORKDIR /frontend

# 외부 패키지 설치를 위해 package.json 복사
COPY package.json /frontend/

RUN npm install

# 나머지 모두 복사
COPY . /frontend/

# 도커 컨테이너에 접근할 수 있게 포트 열어주기
EXPOSE 5173

# 앱 실행시키기
CMD [ "yarn", "dev" ]
#